version: "3.9"
services:
    ubuntu-server:
        image: ubuntu:latest
        command:
            - /bin/bash
            - -c
            - |
              apt update && apt upgrade -y 
              apt install net-tools -y
              apt install iputils-ping -y
              apt install curl -y
              apt install traceroute -y
              tail -f /dev/null
        tty: true
        stdin_open: true
        volumes:
          - c:\docker\data:/data